--- 
festival: 
  outputs: 
    dev: 
      type: "postgres"
      host: "localhost"
      user: "festival_read_write"
      password: "jocund-SCUM-moisten-haggle"
      dbname: "music_festival"
      port: 5432
      schema: "analytics"
  target: dev
